spring:
  jpa:
    generate-ddl: true
    mapping-resources:
      - hbm/user.xml

    properties:
      hibernate:
        id:
          new_generator_mappings: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl